steps:
  # 1. Build Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/macatung-portfolio:$BUILD_ID'
      - '-t'
      - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/macatung-portfolio:latest'
      - '.'

  # 2. Push Image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/macatung-portfolio:$BUILD_ID'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/macatung-portfolio:latest'

  # 3. Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'macatung-portfolio'
      - '--image'
      - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/macatung-portfolio:$BUILD_ID'
      - '--region'
      - 'asia-southeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars=APP_ENV=production,APP_DEBUG=false,APP_KEY=base64:VV+neAI5UBhOaZAIDs8xw53vbkBqZ0tLVscnFZNvcFw=,APP_URL=https://macatung.dev,APP_BASE_DOMAIN=macatung.dev,DB_CONNECTION=sqlite,DB_DATABASE=/var/www/html/database/database.sqlite,SESSION_DRIVER=file,CACHE_STORE=file,LOG_CHANNEL=stderr'

images:
  - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/macatung-portfolio:$BUILD_ID'
  - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/macatung-portfolio:latest'

options:
  logging: CLOUD_LOGGING_ONLY
