import { computed, ref } from 'vue';

export type Locale = 'en' | 'vi';

const locale = ref<Locale>('en');
let initialized = false;

const messages: Record<Locale, Record<string, string>> = {
  en: {
    'nav.home': 'Home', 'nav.projects': 'Projects', 'nav.desktop': 'Desktop', 'nav.blog': 'Blog',
    'nav.game': 'Game 🎮', 'nav.talisman': 'Dev Talisman', 'nav.theravada': 'Meditation 🧘',
    'nav.summon': 'Summon', 'nav.summonDeveloper': 'Summon a Developer', 'nav.menu': 'Toggle mobile menu',
    'nav.new': 'NEW', 'nav.hot': 'HOT', 'nav.zen': 'ZEN', 'brand.tagline': 'Code at midnight',
    'footer.backToTop': 'Back to top', 'footer.lore': 'Grimoire & Lore', 'footer.night': 'Midnight Kingdom',
    'footer.philosophy': 'Humanistic Philosophy', 'footer.manifesto': 'Night Code & Manifesto',
    'footer.systems': 'Grimoire Systems', 'footer.labs': 'Labs & Artifacts', 'footer.projectVault': 'Project Grimoire',
    'footer.arcade': 'Rune Typer Arcade', 'footer.forge': 'Talisman Forge', 'footer.tools': 'Tools & Interaction',
    'footer.altar': 'Summoning Altar', 'footer.status': 'System Status', 'footer.admin': 'CMS Admin',
    'footer.crafted': 'Crafted with', 'footer.heartTitle': 'Click to activate the Midnight Love Easter Egg',
    'footer.copyright': '© 2026 macatung.dev — Crafted with Laravel 11, Inertia.js, Vue 3 & Midnight Magic.',
    'common.breadcrumb': 'Breadcrumb', 'common.readMore': 'Read article', 'common.enter': 'Enter this realm', 'common.copy': 'Copy', 'common.copied': 'Copied', 'common.language': 'Language',
    'common.continue': 'Continue the journey', 'common.nextRealms': 'Explore the next realms',
    'common.consult': 'Or summon a solution consultation now', 'common.minutes': 'min read', 'common.views': 'views',
    'home.blogTitle': 'Architecture & Tech Notes', 'home.blogDescription': 'Deep dives into autonomous Multi-Agent AI, GIS routing algorithms and high-scale engineering.',
    'home.readAllBlog': 'Read all blog posts', 'home.viewDetails': 'View article details',
    'home.gameTitle': 'Rune Typer: Exorcist Keyboard', 'home.gameDescription': 'Destroy bugs with your keyboard, feel authentic mechanical thock, build x5 combos and hunt Boss Bugs.',
    'home.playGame': 'Play Rune Typer', 'home.talismanTitle': 'Developer Talisman Forge', 'home.talismanDescription': 'Create developer charms and export HD canvas artwork for your laptop or social posts.',
    'home.openForge': 'Open Talisman Forge', 'home.terminalDescription': 'A virtual zsh environment with 11 magic commands, arrow-key history and mechanical typing sounds.',
    'projects.title': 'Project Grimoire', 'projects.breadcrumb': 'Project Grimoire', 'about.breadcrumb': 'Philosophy & Manifesto',
    'contact.breadcrumb': 'Summoning Altar (Contact)', 'talisman.breadcrumb': 'Developer Talisman Forge', 'game.breadcrumb': 'Arcade Chamber',
    'blog.breadcrumb': 'Midnight Tech Chronicle', 'blog.title': 'Architecture & Night Tech Notes', 'blog.description': 'Deep dives into autonomous Multi-Agent AI, high-scale backends, GIS and real-world system design.',
    'blog.search': 'Search posts, technologies...', 'blog.all': 'All topics', 'blog.empty': 'No matching articles',
    'blog.emptyHint': 'Try another keyword or choose “All topics”.', 'blog.read': 'Read article',
    'desktop.badge': 'WINDOWS DESKTOP COMPANION', 'desktop.title': 'Solve tasks faster,', 'desktop.titleAccent': 'right on your desktop.',
    'desktop.description': 'Task Companion is a desktop mascot connected directly to Task Hub. Pick a task, open the right workspace and hand a context pack to Codex, Antigravity or Claude Code.',
    'desktop.download': 'Download for Windows', 'desktop.openHub': 'Open Task Hub', 'desktop.free': 'Windows 10/11 · Free · Auto-updated via GitHub Releases',
    'desktop.workflow': 'From task to review-ready result', 'desktop.changelog': 'View changelog and releases on GitHub →',
    'game.title': 'Arcade Chamber: ', 'game.openTerminal': 'Open Terminal', 'game.viewProjects': 'View Projects', 'game.spellbook': 'Spellbook Reference',
    'talisman.badge': 'Dev Artifact Creator', 'talisman.title': 'Talisman Forge', 'talisman.description': 'Customize bug-banishing charms, midnight deploy protection and high-quality artwork for your laptop or social posts.',
    'hero.status': 'READY FOR YOUR QUEST', 'hero.badge': 'LIVE', 'hero.headline': 'Building', 'hero.headlineAccent': 'AI systems.',
    'hero.description': 'I build AI agents, automation systems and software products that help real businesses operate better — from problem framing and architecture to production. Backend engineering, distributed systems and product thinking, with 8+ years of hands-on experience.',
    'hero.explore': 'Explore my work', 'hero.conversation': 'Start a conversation', 'hero.game': 'Play Dev Game', 'hero.profile': 'Skills & Profile', 'hero.cv': 'Download CV', 'hero.cvTitle': 'View & download professional profile', 'hero.years': '> 8 Years Shipping', 'hero.latency': '< 18ms Latency', 'hero.robusta': '100% Robusta Flow', 'hero.zeroBugs': '0 Bugs in Production', 'hero.phase': 'Life Rhythm', 'hero.realTime': 'Live Time', 'hero.statsSpells': '150+ Spells', 'hero.statsLeaderboard': 'Hall of Fame', 'hero.statsAudio': 'Web Audio SFX',
    'terminal.badge': 'Interactive REPL Shell', 'terminal.title': 'Midnight', 'terminal.titleAccent': 'Terminal CLI',
    'phase.midnight.vietnameseName': 'Magical Midnight', 'phase.midnight.greeting': 'Good evening, dark traveler!', 'phase.midnight.status': 'READY FOR QUEST 00:00 AM', 'phase.midnight.tagline': 'The world sleeps; the code awakens', 'phase.midnight.theme': 'When the mind tunes into the universe: zero distraction, maximum output.',
    'phase.dawn.vietnameseName': 'Amber Dawn', 'phase.dawn.greeting': 'Good morning — a bright new beginning!', 'phase.dawn.status': 'CHARGING MORNING ENERGY & STANDUP', 'phase.dawn.tagline': 'Early coffee, full spirit restored', 'phase.dawn.theme': 'Fresh air, clear thinking, ready to architect and plan the mission.',
    'phase.afternoon.vietnameseName': 'Cyber High Noon', 'phase.afternoon.greeting': 'A productive afternoon — ship the feature!', 'phase.afternoon.status': 'SHIPPING PEAK FEATURES & REVIEWING', 'phase.afternoon.tagline': 'Full focus, breakthrough velocity', 'phase.afternoon.theme': 'Tune performance, review clean code and deploy resilient solutions.',
    'phase.twilight.vietnameseName': 'Violet Twilight', 'phase.twilight.greeting': 'The sun sets; the night rises!', 'phase.twilight.status': 'STARTING NIGHT SHIFT & REFACTORING', 'phase.twilight.tagline': 'Neon lights on, the spell begins', 'phase.twilight.theme': 'Shift energy from day to night and warm up for the midnight session.',
    'time.travel': 'Time Travel', 'time.travelDescription': "Explore the Developer's four daily phases", 'time.active': 'Active', 'time.caffeine': 'Caffeine', 'time.live': 'Live time', 'time.reset': 'Return to live time', 'time.coffee': 'Morning coffee', 'time.sunglasses': 'Sunglasses', 'time.talisman': 'Talisman',
    'skills.badge': 'Technical Arsenal', 'skills.title': 'Skills &', 'skills.titleAccent': 'Technology', 'skills.description': '18 core skills forged through distributed systems, high-scale web apps and creative interfaces.', 'skills.search': 'Filter skills (Vue, Go, Redis)...', 'skills.guarantee': '100% Tested, Type-Safe & Zero Runtime Crash', 'skills.guaranteeDescription': 'Every module is covered by automated tests, follows SOLID principles and is optimized for low latency.',
    'experience.badge': 'The Career Chronicles', 'experience.title': 'Experience &', 'experience.titleAccent': 'Chronicles', 'experience.description': 'A trail through high-scale production projects, from Indie Hacker to Lead Systems Architect.', 'experience.all': 'All milestones', 'experience.contract': 'Contract & Creative', 'experience.openSource': 'Indie & Open Source', 'experience.quest': 'Midnight Quest',
    'projects.all': 'All Projects', 'projects.architecture': 'Architecture Projects', 'projects.featured': 'Featured', 'projects.works': 'Works &', 'projects.worksAccent': 'Production', 'projects.description': 'Distributed systems, high-scale web apps and creative tools forged during quiet coding sessions.', 'projects.search': 'Search technologies, names...', 'projects.viewAll': 'View all 6+ projects', 'projects.empty': 'No matching projects', 'projects.emptyHint': 'Try another keyword or choose “All Projects”.', 'projects.details': 'View Architecture Details', 'projects.archive': 'Architecture Archive', 'projects.exploreAll': 'Explore all deep-dive projects', 'projects.enterprise': 'Enterprise NDA project',
    'about.badge': 'The Midnight Architect', 'about.title': 'Humanistic', 'about.titleAccent': 'Engineering', 'about.description': 'Technology should amplify human potential, not replace it.', 'about.origin': 'Senior Fullstack & AI Agent Architect', 'about.award': 'National Informatics Award · 8+ Years of High-Scale Systems', 'about.location': 'Ho Chi Minh City / Remote', 'about.principle': '🌿 Humanistic Engineering',
    'contact.title': 'Summoning Altar', 'contact.description': 'Have a system to build, a problem to untangle or a midnight idea? Send a signal.', 'contact.name': 'Your name', 'contact.email': 'Email address', 'contact.message': 'Tell me about the quest...', 'contact.submit': 'Send the signal', 'home.arcadeBadge': 'Dev Arcade Chamber', 'home.artifactsBadge': 'Developer Artifacts',
  },
  vi: {
    'nav.home': 'Trang Chủ', 'nav.projects': 'Dự Án', 'nav.desktop': 'Desktop', 'nav.blog': 'Blog',
    'nav.game': 'Game 🎮', 'nav.talisman': 'Bùa Dev', 'nav.theravada': 'Tọa Thiền 🧘', 'nav.summon': 'Triệu Hồi',
    'nav.summonDeveloper': 'Triệu Hồi Lập Trình Viên', 'nav.menu': 'Mở menu di động', 'nav.new': 'MỚI', 'nav.hot': 'HOT', 'nav.zen': 'ZEN',
    'brand.tagline': 'Code lúc nửa đêm', 'footer.backToTop': 'Về đầu trang', 'footer.lore': 'Grimoire & Lore', 'footer.night': 'Vương Quốc Đêm',
    'footer.philosophy': 'Triết Lý Vị Nhân Sinh', 'footer.manifesto': 'Bản Lĩnh Đêm & Manifesto', 'footer.systems': 'Hệ Thống Grimoire',
    'footer.labs': 'Thí Nghiệm & Pháp Bảo', 'footer.projectVault': 'Kho Dự Án Grimoire', 'footer.arcade': 'Phòng Máy Rune Typer', 'footer.forge': 'Lò Luyện Bùa Chú',
    'footer.tools': 'Công Cụ & Tương Tác', 'footer.altar': 'Bàn Thờ Triệu Hồi', 'footer.status': 'Trạng Thái Hệ Thống', 'footer.admin': 'Quản Trị CMS',
    'footer.crafted': 'Crafted with', 'footer.heartTitle': 'Bấm để kích hoạt Midnight Love Easter Egg', 'footer.copyright': '© 2026 macatung.dev — Crafted with Laravel 11, Inertia.js, Vue 3 & Midnight Magic.',
    'common.breadcrumb': 'Breadcrumb', 'common.readMore': 'Xem chi tiết bài viết', 'common.enter': 'Bước vào cõi này', 'common.continue': 'Tiếp tục hành trình', 'common.nextRealms': 'Khám phá các cõi tiếp theo', 'common.consult': 'Hoặc triệu hồi tư vấn giải pháp ngay', 'common.minutes': 'phút đọc', 'common.views': 'lượt đọc', 'common.copy': 'Chép', 'common.copied': 'Đã chép', 'common.language': 'Ngôn ngữ',
    'home.blogTitle': 'Ghi Chép Kiến Trúc & Blog', 'home.blogDescription': 'Các bài phân tích chuyên sâu về Multi-Agent AI tự trị, giải thuật GIS và kỹ thuật chịu tải cao.', 'home.readAllBlog': 'Đọc toàn bộ blog', 'home.viewDetails': 'Xem chi tiết bài viết', 'home.gameTitle': 'Rune Typer: Thần Phím Trừ Tà', 'home.gameDescription': 'Gõ phím diệt Bug, cảm nhận âm thanh thock, chuỗi combo x5 và săn Boss Bug.', 'home.playGame': 'Vào chơi Rune Typer', 'home.talismanTitle': 'Lò Rèn Bùa Hộ Mệnh Lập Trình Viên', 'home.talismanDescription': 'Tạo bùa hộ mệnh dev và tải file ảnh HD để dán laptop hoặc chia sẻ.', 'home.openForge': 'Mở lò rèn bùa Dev', 'home.terminalDescription': 'Môi trường zsh ảo với 11 câu lệnh ma thuật, lịch sử phím mũi tên và âm thanh gõ phím cơ học.',
    'projects.title': 'Kho Grimoire Dự Án', 'projects.breadcrumb': 'Kho Dự Án (Grimoire)', 'about.breadcrumb': 'Triết Lý & Tuyên Ngôn (Manifesto)', 'contact.breadcrumb': 'Điện Thờ Triệu Hồi (Contact)', 'talisman.breadcrumb': 'Lò Rèn Bùa Hộ Mệnh', 'game.breadcrumb': 'Phòng Máy Arcade', 'blog.breadcrumb': 'Midnight Tech Chronicle', 'blog.title': 'Ghi Chép Kiến Trúc & Kỹ Thuật Đêm', 'blog.description': 'Các bài viết chuyên sâu về Multi-Agent AI, backend chịu tải cao, GIS và thiết kế hệ thống thực chiến.', 'blog.search': 'Tìm kiếm bài viết, công nghệ...', 'blog.all': 'Tất cả chủ đề', 'blog.empty': 'Chưa có bài viết phù hợp', 'blog.emptyHint': 'Hãy thử từ khóa khác hoặc chọn “Tất cả chủ đề”.', 'blog.read': 'Đọc bài viết',
    'desktop.badge': 'WINDOWS DESKTOP COMPANION', 'desktop.title': 'Giải quyết task nhanh hơn,', 'desktop.titleAccent': 'ngay trên desktop.', 'desktop.description': 'Task Companion là mascot desktop kết nối trực tiếp với Task Hub. Chọn task, mở workspace và giao context pack cho Codex, Antigravity hoặc Claude Code.', 'desktop.download': 'Tải cho Windows', 'desktop.openHub': 'Mở Task Hub', 'desktop.free': 'Windows 10/11 · Miễn phí · Cập nhật tự động qua GitHub Releases', 'desktop.workflow': 'Từ task đến kết quả review', 'desktop.changelog': 'Xem changelog và các bản phát hành trên GitHub →', 'game.title': 'Phòng Máy Arcade: ', 'game.openTerminal': 'Mở Terminal', 'game.viewProjects': 'Xem Dự Án', 'game.spellbook': 'Bí Kíp Thần Chú (Spellbook Reference)', 'talisman.badge': 'Dev Artifact Creator', 'talisman.title': 'Lò Rèn Bùa Hộ Mệnh', 'talisman.description': 'Tùy biến bùa trừ Bug, bảo trợ deploy lúc nửa đêm và xuất ảnh chất lượng cao cho laptop hoặc mạng xã hội.',
    'hero.status': 'SẴN SÀNG NHẬN QUEST', 'hero.badge': 'ĐANG LIVE', 'hero.headline': 'Kiến tạo', 'hero.headlineAccent': 'hệ thống AI.', 'hero.description': 'Tôi xây dựng AI Agent, hệ thống tự động hóa và sản phẩm phần mềm giúp doanh nghiệp vận hành tốt hơn — từ định hình bài toán, kiến trúc đến production. Chuyên sâu backend, hệ thống phân tán và tư duy sản phẩm với hơn 8 năm thực chiến.', 'hero.explore': 'Khám phá sản phẩm', 'hero.conversation': 'Bắt đầu trò chuyện', 'hero.game': 'Chơi Dev Game', 'hero.profile': 'Kỹ năng & Hồ sơ', 'hero.cv': 'Tải CV', 'hero.cvTitle': 'Xem & tải hồ sơ năng lực', 'hero.years': '> 8 Năm Thực Chiến', 'hero.latency': '< 18ms Latency', 'hero.robusta': '100% Robusta Flow', 'hero.zeroBugs': '0 Bug Production', 'hero.phase': 'Phân Kỳ Nhịp Sống', 'hero.realTime': 'Giờ Thực', 'hero.statsSpells': '150+ Thần Chú', 'hero.statsLeaderboard': 'Bảng Phong Thần', 'hero.statsAudio': 'Web Audio SFX',
    'terminal.badge': 'Interactive REPL Shell', 'terminal.title': 'Midnight', 'terminal.titleAccent': 'Terminal CLI',
    'phase.midnight.vietnameseName': 'Đêm Sâu Ma Thuật', 'phase.midnight.greeting': 'Chào buổi đêm, lữ khách bóng tối!', 'phase.midnight.status': 'SẴN SÀNG NHẬN QUEST 00:00 AM', 'phase.midnight.tagline': 'Vạn vật say ngủ, dòng code thức giấc', 'phase.midnight.theme': 'Thời điểm tâm trí hòa cùng tần số vũ trụ, zero distraction, năng suất cực đại.', 'phase.dawn.vietnameseName': 'Rạng Đông Hổ Phách', 'phase.dawn.greeting': 'Chào buổi sáng rực rỡ, khởi đầu ngày mới!', 'phase.dawn.status': 'ĐANG TIẾP NĂNG LƯỢNG SÁNG & STANDUP', 'phase.dawn.tagline': 'Tách cà phê sớm, nạp trọn linh khí', 'phase.dawn.theme': 'Không khí trong lành, tư duy minh mẫn, chuẩn bị kiến trúc và lên kế hoạch tác chiến.', 'phase.afternoon.vietnameseName': 'Chính Ngọ Cyber', 'phase.afternoon.greeting': 'Chào buổi chiều năng suất, ship tính năng!', 'phase.afternoon.status': 'ĐANG SHIP TÍNH NĂNG CAO ĐIỂM & REVIEW', 'phase.afternoon.tagline': 'Tập trung cao độ, bứt phá tiến độ', 'phase.afternoon.theme': 'Tối ưu hóa hiệu năng, review code chuẩn chỉ, triển khai các giải pháp kiên cố.', 'phase.twilight.vietnameseName': 'Hoàng Hôn Tím', 'phase.twilight.greeting': 'Hoàng hôn buông xuống, bóng đêm trỗi dậy!', 'phase.twilight.status': 'ĐANG KHỞI ĐỘNG CA ĐÊM & REFACTOR', 'phase.twilight.tagline': 'Ánh đèn neon bật, phù phép bắt đầu', 'phase.twilight.theme': 'Chuyển giao năng lượng từ ngày sang đêm, vươn vai khởi động cho ca thâu đêm.',
    'time.travel': 'Du hành thời gian', 'time.travelDescription': 'Trải nghiệm 4 khung giờ trong ngày của Developer', 'time.active': 'Đang hoạt động', 'time.caffeine': 'Caffeine', 'time.live': 'Giờ thực', 'time.reset': 'Quay lại giờ thực tế', 'time.coffee': 'Ly cafe sáng', 'time.sunglasses': 'Kính râm', 'time.talisman': 'Bùa chú', 'skills.badge': 'Technical Arsenal', 'skills.title': 'Kỹ Năng &', 'skills.titleAccent': 'Công Nghệ', 'skills.description': '18 kỹ năng cốt lõi được tôi luyện qua các hệ thống phân tán, web app tải cao và giao diện sáng tạo.', 'skills.search': 'Lọc kỹ năng (Vue, Go, Redis)...', 'skills.guarantee': '100% Tested, Type-Safe & Zero Runtime Crash', 'skills.guaranteeDescription': 'Mọi module đều được kiểm thử tự động, tuân thủ SOLID và tối ưu hóa latency cực thấp.',
    'experience.badge': 'The Career Chronicles', 'experience.title': 'Kinh Nghiệm &', 'experience.titleAccent': 'Biên Niên Sử', 'experience.description': 'Dấu chân qua các dự án thực chiến tải cao, hành trình phát triển từ Indie Hacker sang Lead Systems Architect.', 'experience.all': 'Tất Cả Mốc Thời Gian', 'experience.contract': 'Contract & Creative', 'experience.openSource': 'Indie & Open Source', 'experience.quest': 'Midnight Quest', 'projects.all': 'Tất Cả Dự Án', 'projects.architecture': 'Dự Án Kiến Trúc', 'projects.featured': 'Tiêu Biểu', 'projects.works': 'Tác Phẩm &', 'projects.worksAccent': 'Thực Chiến', 'projects.description': 'Những hệ thống phân tán, web app tải cao và công cụ sáng tạo được kiến tạo trong những phiên lập trình tĩnh lặng.', 'projects.search': 'Tìm kiếm công nghệ, tên...', 'projects.viewAll': 'Xem Toàn Bộ 6+ Dự Án', 'projects.empty': 'Không tìm thấy dự án phù hợp', 'projects.emptyHint': 'Hãy thử tìm với từ khóa khác hoặc chọn “Tất Cả Dự Án”.', 'projects.details': 'Xem Chi Tiết Kiến Trúc', 'projects.archive': 'Kho Lưu Trữ Kiến Trúc', 'projects.exploreAll': 'Khám Phá Toàn Bộ Dự Án Chuyên Sâu', 'projects.enterprise': 'Dự án doanh nghiệp bảo mật NDA', 'about.badge': 'The Midnight Architect', 'about.title': 'Kỹ Nghệ', 'about.titleAccent': 'Vị Nhân Sinh', 'about.description': 'Công nghệ nên khuếch đại tiềm năng con người, không thay thế con người.', 'about.origin': 'Senior Fullstack & AI Agent Architect', 'about.award': 'Giải Quốc Gia Tin Học · 8+ Năm Thực Chiến Hệ Thống Tải Cao', 'about.location': 'Ho Chi Minh City / Remote', 'about.principle': '🌿 Kỹ Nghệ Vị Nhân Sinh', 'contact.title': 'Điện Thờ Triệu Hồi', 'contact.description': 'Bạn có hệ thống cần xây, bài toán cần gỡ rối hay ý tưởng lúc nửa đêm? Hãy gửi tín hiệu.', 'contact.name': 'Tên của bạn', 'contact.email': 'Địa chỉ email', 'contact.message': 'Kể về quest của bạn...', 'contact.submit': 'Gửi tín hiệu'
  },
};

Object.assign(messages.vi, {
  'common.share': 'Chia sẻ', 'common.copyLink': 'Sao chép liên kết', 'theravada.timeTraveler': 'Tua Giờ Thiền Môn 24H',
  'theravada.paperMode': 'Nền Giấy', 'theravada.nightMode': 'Nền Đêm', 'theravada.leaves': 'Lá Rơi', 'theravada.candle': 'Đèn Dầu', 'theravada.focus': 'Tập Trung', 'theravada.bell': 'Thỉnh Chuông', 'theravada.glossaryHint': 'Rê chuột hoặc nhấp vào thuật ngữ gạch chân để xem chú giải.', 'theravada.inArticleGlossary': 'Chú Giải Thuật Ngữ Pāḷi Trong Bài', 'theravada.shareTitle': 'Lan Tỏa Chánh Pháp Đến Muôn Người', 'theravada.shareDescription': 'Chia sẻ bài kinh đến người thân và đạo hữu để gieo duyên lành giải thoát.', 'theravada.backHome': 'Quay lại trang chủ Theravāda', 'theravada.switchNight': 'Chuyển sang nền đêm', 'theravada.switchPaper': 'Chuyển sang nền giấy', 'theravada.toggleLeaves': 'Bật/tắt hiệu ứng lá rơi', 'theravada.toggleCandle': 'Chế độ đèn dầu thiền quán', 'theravada.toggleFocus': 'Chế độ đọc tập trung', 'theravada.ringBell': 'Thỉnh chuông chánh niệm', 'theravada.shareArticle': 'Chia sẻ bài kinh', 'theravada.decreaseFont': 'Giảm cỡ chữ', 'theravada.increaseFont': 'Tăng cỡ chữ',
  'terminal.copyLog': 'Sao chép nhật ký', 'terminal.collapse': 'Thu nhỏ', 'terminal.expand': 'Mở rộng', 'terminal.placeholder': 'Nhập spell (vd: help, cv, projects)...',
  'home.arcadeBadge': 'Dev Arcade Chamber', 'home.artifactsBadge': 'Developer Artifacts',
  'about.tabFlow': 'Trạng Thái 00:00 AM', 'about.tabFlowSubtitle': 'Ultra-Flow State giữa đêm sâu — không phân tâm, tối ưu tư duy giải thuật.', 'about.tabFlowContent': 'Khi cả thành phố chìm vào giấc ngủ, không còn họp hành hay tin nhắn ngắt quãng. Đêm sâu là không gian tĩnh tại để giải quyết các bài toán kiến trúc hóc búa và đưa tư duy vào trạng thái Ultra-Flow thuần khiết.', 'about.tabScale': 'Kiến Trúc Tải Cao', 'about.tabScaleSubtitle': '8+ năm thực chiến hệ thống phân tán, xử lý hàng triệu requests với latency < 18ms.', 'about.tabScaleContent': 'Chuyên sâu tối ưu hóa cơ sở dữ liệu lớn, caching đa tầng, hệ thống hàng đợi bất đồng bộ và cam kết SLA 99.9% Uptime cho các nền tảng doanh nghiệp.', 'about.tabAgents': 'Multi-Agent AI Tự Trị', 'about.tabAgentsSubtitle': 'Tiên phong tích hợp AI Agents thế hệ mới phục vụ tự động hóa quy trình nghiệp vụ.', 'about.tabAgentsContent': 'Thiết kế các Agent thông minh với Tool Calling, Semantic Search và kết nối MCP, giải phóng sức lao động con người với độ chính xác và an toàn dữ liệu cao.', 'about.tabFullstack': 'Kỹ Nghệ Toàn Diện', 'about.tabFullstackSubtitle': 'Làm chủ từ giao diện tương tác kỳ ảo đến hạ tầng đám mây kiên cố.', 'about.tabFullstackContent': 'Kết hợp Frontend mượt mà với Backend vững chắc, Docker và GCP Cloud, tuân thủ nghiêm ngặt chuẩn bảo mật OWASP.',
  'about.statsViews': 'Tổng Lượt Truy Cập Live', 'about.statsViewsDesc': 'Pageviews ghi nhận bởi Analytics', 'about.statsProjects': 'Dự Án Đang Chạy', 'about.statsProjectsDesc': 'Sản phẩm kỹ thuật trong CMS', 'about.statsHops': 'Lượt Nhảy Linh Vật', 'about.statsHopsDesc': 'Tương tác vật lý Ma Cà Tưng', 'about.statsReady': 'Tỷ Lệ Sẵn Sàng 00:00 AM', 'about.statsReadyDesc': 'Mức độ tập trung khi vào flow', 'about.pillarLatency': 'Tối Ưu Độ Trễ (<18ms)', 'about.pillarLatencyDesc': 'Bộ nhớ đệm đa tầng, index cơ sở dữ liệu chuyên sâu và truy vấn bất đồng bộ non-blocking.', 'about.pillarElastic': 'Co Giãn Linh Hoạt (Elastic)', 'about.pillarElasticDesc': 'Kiến trúc container hóa, microservices và hàng đợi sẵn sàng mở rộng khi lưu lượng tăng đột biến.', 'about.pillarQuality': 'Chất Lượng Phòng Vệ (Zero-Crash)', 'about.pillarQualityDesc': '100% Strict TypeScript, tự động hóa CI/CD, unit testing bao phủ và bảo mật đa tầng.', 'about.sectionTitle': 'Triết Lý &', 'about.sectionAccent': 'Bản Lĩnh Đêm', 'about.sectionDescription': 'Những con số thực chiến và nguyên tắc kỹ thuật được tôi luyện qua hàng ngàn đêm đối mặt với màn hình đen.', 'about.fallbackExperience': 'Practical Experience', 'about.fallbackExperienceDesc': 'Since 2017 across high-scale systems & AI agents', 'about.fallbackAutomation': 'Automation Rate', 'about.fallbackAutomationDesc': 'Multi-Agent AI handles support & refunds 24/7', 'about.fallbackInfra': 'GIS & Infrastructure', 'about.fallbackInfraDesc': 'Fiber network & NMS equipment management', 'about.fallbackUptime': 'Night-Shift Uptime', 'about.fallbackUptimeDesc': 'High-scale architecture & zero downtime',
  'contact.badge': 'Liên Hệ Trực Tiếp & Gửi Quest', 'contact.heading': 'Bàn Thờ', 'contact.headingAccent': 'Triệu Hồi', 'contact.descriptionFull': 'Gửi tín hiệu qua màn đêm để khởi động dự án mới, hợp tác kiến trúc hoặc tải hồ sơ năng lực.', 'contact.channel': 'Kênh Thần Giao Cách Cảm', 'contact.channelDesc': 'Mọi thông điệp gửi đến đều được xử lý trực tiếp bởi Alchemist trong khung giờ 00:00 - 05:00 AM.', 'contact.directEmail': 'Email Trực Tiếp', 'contact.copied': 'Đã Copy', 'contact.timezone': 'Múi Giờ Hoạt Động:', 'contact.questStatus': 'Trạng Thái Quest:', 'contact.available': 'Sẵn Sàng Nhận Dự Án', 'contact.responseTime': 'Thời Gian Hồi Đáp:', 'contact.responsePromise': '< 24 Giờ Cam Kết', 'contact.network': 'Mạng Lưới Kỹ Thuật Số & Hồ Sơ', 'contact.updated': 'Cập nhật tháng 08/2026', 'contact.viewCv': 'Xem / Tải CV', 'contact.success': 'Triệu Hồi Thành Công!', 'contact.successDesc': 'Tín hiệu đã được truyền đi qua màn đêm. Mã biên nhận:', 'contact.successTail': 'Alchemist sẽ hồi đáp bạn sớm nhất!', 'contact.sendAnother': 'Gửi Thêm Lời Triệu Hồi Khác', 'contact.nameLabel': '1. Tên Lữ Khách / Kỹ Sư', 'contact.emailLabel': '2. Địa Chỉ Thần Giao (Email)', 'contact.typeLabel': '3. Loại Quest / Nhiệm Vụ Hợp Tác', 'contact.coffeeLabel': '4. Lễ Vật Cà Phê Tiếp Sức', 'contact.messageLabel': '5. Chi Tiết Nhiệm Vụ & Kỳ Vọng', 'contact.messagePlaceholder': 'Mô tả mục tiêu dự án, thời gian dự kiến và bất kỳ yêu cầu kiến trúc đặc thù nào...', 'contact.submitting': 'Đang Truyền Tín Hiệu...', 'contact.submit': 'Khởi Động Triệu Hồi Ma Cà Tưng', 'contact.projectOther': 'Quest Khác', 'contact.coffeeSalt': '1 Ly Cà Phê Muối Nửa Đêm', 'contact.coffeeEspresso': 'Espresso Đậm Đặc Double Shot', 'contact.coffeeTea': 'Trà Đào Cam Sả',
  'mascot.sleeping': '😴 Zzz... Sleeping... (Traveler away)...', 'mascot.expand': 'Expand companion', 'mascot.collapse': 'Minimize to icon', 'mascot.hops': 'hops', 'mascot.pet': 'Ma Cà Tưng Pet', 'mascot.coffee': 'Coffee', 'mascot.coffeeTitle': 'Give Robusta coffee', 'mascot.talisman': 'Seal charm', 'mascot.talismanTitle': 'Apply 0-Bug talisman', 'mascot.petAction': 'Headpat', 'mascot.petTitle': 'Pet Ma Cà Tưng', 'mascot.time': 'Time travel', 'mascot.timeTitle': 'Toggle the 24H time machine', 'mascot.summon': 'Summon Ma Cà Tưng', 'mascot.summonTitle': 'Summon Ma Cà Tưng / Contact',
  'projectModal.featured': 'Kiến Trúc Tiêu Biểu', 'projectModal.nda': 'Enterprise NDA', 'projectModal.overview': 'Tổng Quan Giải Pháp', 'projectModal.metrics': 'Hiệu Năng & Chỉ Số Thực Chiến', 'projectModal.highlights': 'Kiến Trúc & Điểm Nhấn Kỹ Thuật', 'projectModal.security': 'Bảo Mật & Bản Quyền Doanh Nghiệp (Enterprise NDA)', 'projectModal.securityText': 'Đây là hệ thống chuyên dụng phục vụ hạ tầng và nghiệp vụ doanh nghiệp. Nhằm tuân thủ thỏa thuận bảo mật dữ liệu khách hàng, mã nguồn và môi trường live production không được công khai.', 'projectModal.summon': 'Triệu Hồi Tư Vấn Giải Pháp', 'projectModal.readArticle': 'Đọc Bài Viết Kiến Trúc', 'projectModal.close': 'Đóng [ESC]', 'projectModal.closeAria': 'Đóng popup',
  'game.rankMaster': '🧙‍♂️ Thần Phím Đại Tông Sư (Master Exorcist)', 'game.rankSlayer': '⚡ Pháp Sư Trảm Bug (Bug Slayer)', 'game.rankCoder': '🌙 Đạo Sĩ Luyện Code (Rune Coder)', 'game.rankApprentice': '🌱 Tập Sự 0 Bug (Apprentice)', 'game.description': 'Gõ code thần chú rơi từ bầu trời đêm để trấn yểm Bug và rèn luyện phản xạ bàn phím cơ.', 'game.beginner': 'Tập Sự 0 Bug (30s)', 'game.normal': 'Ma Đạo 00:00 AM (60s)', 'game.boss': 'Sinh Tồn Boss Bug (5 ❤️)', 'game.score': 'Điểm Số', 'game.lives': 'Mạng Sống', 'game.time': 'Thời Gian', 'game.speed': 'Tốc Độ', 'game.accuracy': 'Chính Xác', 'game.best': 'Kỷ Lục', 'game.mute': 'Bật Âm Thanh', 'game.unmute': 'Tắt Âm Thanh', 'game.fullscreen': 'Toàn Màn Hình', 'game.resume': 'Tiếp Tục', 'game.pause': 'Tạm Dừng', 'game.start': 'Vào Chơi Ngay', 'game.startHint': 'Nhấn phím bất kỳ hoặc click để bắt đầu gõ', 'game.paused': 'Đang Tạm Dừng', 'game.pauseHint': 'Nghỉ tay uống ngụm cà phê Robusta', 'game.end': 'Kết Thúc Phiên Trừ Tà!', 'game.totalScore': 'Tổng Điểm', 'game.wpm': 'Tốc Độ Gõ', 'game.replay': 'Chơi Lại', 'game.leaderboard': 'Xem Kỷ Lục', 'game.noScores': 'Chưa có kỷ lục nào. Hãy là người đầu tiên ghi danh!', 'game.cast': '✨ Trảm Bug!',
  'forge.title': 'Lò Luyện Bùa', 'forge.titleAccent': 'Lập Trình', 'forge.description': 'Chọn thần chú hộ mệnh, điền tên và tâm nguyện, sau đó thực hiện nghi thức Khai Quang để nhận phúc khí 0-bug cho toàn bộ repository.', 'forge.presets': '1. Chọn Thần Chú Bùa Chú', 'forge.author': '2. Tên Kỹ Sư (Author)', 'forge.wish': '3. Nguyện Ước / Lời Chúc', 'forge.palette': '4. Khí Sắc Bùa (Color Palette)', 'forge.blessing': 'Khai Quang Trì Chú', 'forge.blessingAgain': 'Khai Quang Lại', 'forge.blessingProgress': 'Đang Niệm Chú Khai Quang...', 'forge.copy': 'Copy ASCII Card', 'forge.copied': 'Đã Copy ASCII!', 'forge.owner': 'Kỹ Sư:', 'forge.wishValue': 'Nguyện:', 'forge.blessed': '✓ ĐÃ KHAI QUANG', 'forge.notBlessed': '[CHƯA KHAI QUANG]',
  'theravada.brand': 'Ma Tọa Thiền', 'theravada.tagline': 'Chánh Niệm Từng Giây • Theravāda', 'theravada.home': 'Về Trang Chủ Macatung.dev', 'theravada.ehipassiko': 'EHIPASSIKO — HÃY ĐẾN ĐỂ THẤY & THỂ NGHIỆM', 'theravada.heroTitle': 'Vượt Khỏi Đêm Đen Vô Minh', 'theravada.heroAccent': 'Hướng Về Ánh Sáng Chánh Tri Kiến', 'theravada.heroQuote': 'Dù là Ma Cà Tưng lang thang trong bóng đêm vô minh, khi có duyên lành hạnh ngộ Chánh Pháp cũng buông bỏ vọng niệm để tọa thiền, nương tựa Tam Bảo tìm về sự an tịnh và giải thoát tối hậu.', 'theravada.study': 'Khảo Cứu Pháp Học', 'theravada.practice': 'Thực Hành Thiền Vipassanā', 'theravada.chanting': 'Kinh Tụng Pāḷi', 'theravada.history': 'Lịch Sử Phật Giáo', 'theravada.glossary': 'Từ Điển Pāḷi', 'theravada.verse': 'Kinh Pháp Cú (Dhammapada) — Kệ số', 'theravada.reflect': 'Lắng Lòng Chiêm Nghiệm', 'theravada.pillars': 'Tứ Đại Trụ Cột Hoằng Dương Theravāda', 'theravada.pillarsDesc': 'Học hiểu tường tận giáo pháp, lịch sử truyền thừa và thể nghiệm chân lý trong từng khoảnh khắc', 'theravada.explore': 'Khám phá chuyên mục', 'theravada.core': 'Thánh Điển & Giáo Lý Cốt Lõi', 'theravada.recent': 'Kinh Văn & Bài Học Gần Đây', 'theravada.read': 'Đọc bài', 'theravada.minutes': 'phút đọc', 'theravada.articles': 'Bài viết',
  'page.aboutTitle': 'Skills & Professional Profile', 'page.aboutDescription': 'Explore the software journey, technical skills, production experience and architecture manifesto.', 'page.projectsTitle': 'Project Grimoire — Production Systems', 'page.projectsDescription': 'Explore software products, system architectures, interactive applications and open-source work.', 'page.contactTitle': 'Summoning & Technical Consultation', 'page.contactDescription': 'Send a summoning message or connect for software development and architecture consulting.', 'page.terminalDescription': 'A virtual zsh shell with 11 magic commands, arrow-key history and mechanical typing sounds.',
});

Object.assign(messages.en, {
  'common.share': 'Share', 'common.copyLink': 'Copy link', 'theravada.timeTraveler': '24H Meditation Time Traveler',
  'theravada.paperMode': 'Paper Mode', 'theravada.nightMode': 'Night Mode', 'theravada.leaves': 'Falling Leaves', 'theravada.candle': 'Candlelight', 'theravada.focus': 'Focus Mode', 'theravada.bell': 'Mindfulness Bell', 'theravada.glossaryHint': 'Hover or click an underlined term to view its explanation.', 'theravada.inArticleGlossary': 'Pāḷi Terms in This Article', 'theravada.shareTitle': 'Share the Dhamma', 'theravada.shareDescription': 'Share this article with friends and fellow practitioners to spread a seed of liberation.', 'theravada.backHome': 'Back to Theravāda home', 'theravada.switchNight': 'Switch to night background', 'theravada.switchPaper': 'Switch to paper background', 'theravada.toggleLeaves': 'Toggle falling leaves', 'theravada.toggleCandle': 'Toggle contemplative candlelight', 'theravada.toggleFocus': 'Toggle focus reading mode', 'theravada.ringBell': 'Ring mindfulness bell', 'theravada.shareArticle': 'Share this article', 'theravada.decreaseFont': 'Decrease font size', 'theravada.increaseFont': 'Increase font size',
  'terminal.copyLog': 'Copy terminal log', 'terminal.collapse': 'Collapse terminal', 'terminal.expand': 'Expand terminal', 'terminal.placeholder': 'Type a spell (e.g. help, cv, projects)...',
  'about.tabFlow': 'Midnight 00:00 State', 'about.tabFlowSubtitle': 'Ultra-Flow state in the deep night — zero distraction, pure algorithmic focus.', 'about.tabFlowContent': 'When the city sleeps, there are no meetings or interruptions. Deep night becomes a quiet space to solve hard architecture problems and enter a pure Ultra-Flow state.', 'about.tabScale': 'High-Scale Architecture', 'about.tabScaleSubtitle': '8+ years shipping distributed systems and millions of requests under 18ms latency.', 'about.tabScaleContent': 'Deep expertise in large databases, multi-layer caching, asynchronous queues and 99.9% uptime SLAs for enterprise platforms.', 'about.tabAgents': 'Autonomous Multi-Agent AI', 'about.tabAgentsSubtitle': 'Next-generation AI agents for practical business automation.', 'about.tabAgentsContent': 'Design intelligent agents with tool calling, semantic search and MCP integrations that amplify human work with accuracy and data safety.', 'about.tabFullstack': 'Full-Stack Craft', 'about.tabFullstackSubtitle': 'From magical interactive interfaces to resilient cloud infrastructure.', 'about.tabFullstackContent': 'A balanced blend of Vue, TypeScript, Web Audio and Canvas with Laravel, Docker and GCP, guided by OWASP security standards.',
  'about.statsViews': 'Live Pageviews', 'about.statsViewsDesc': 'Pageviews tracked by Analytics', 'about.statsProjects': 'Active Projects', 'about.statsProjectsDesc': 'Technical products in the CMS', 'about.statsHops': 'Mascot Hops', 'about.statsHopsDesc': 'Ma Cà Tưng physical interactions', 'about.statsReady': '00:00 Readiness', 'about.statsReadyDesc': 'Focus level when entering flow', 'about.pillarLatency': 'Latency Optimized (<18ms)', 'about.pillarLatencyDesc': 'Multi-layer caching, deep database indexes and non-blocking async queries.', 'about.pillarElastic': 'Elastic by Design', 'about.pillarElasticDesc': 'Containerized architecture, microservices and queues ready for sudden traffic spikes.', 'about.pillarQuality': 'Zero-Crash Quality', 'about.pillarQualityDesc': 'Strict TypeScript, automated CI/CD, broad unit coverage and defense-in-depth security.', 'about.sectionTitle': 'Philosophy &', 'about.sectionAccent': 'Night Code', 'about.sectionDescription': 'Production numbers and engineering principles forged through thousands of nights facing a black screen.', 'about.fallbackExperience': 'Practical Experience', 'about.fallbackExperienceDesc': 'Since 2017 across high-scale systems & AI agents', 'about.fallbackAutomation': 'Automation Rate', 'about.fallbackAutomationDesc': 'Multi-Agent AI handles support & refunds 24/7', 'about.fallbackInfra': 'GIS & Infrastructure', 'about.fallbackInfraDesc': 'Fiber network & NMS equipment management', 'about.fallbackUptime': 'Night-Shift Uptime', 'about.fallbackUptimeDesc': 'High-scale architecture & zero downtime',
  'contact.badge': 'Direct Contact & Quest Inquiry', 'contact.heading': 'Summoning', 'contact.headingAccent': 'Altar', 'contact.descriptionFull': 'Send a signal through the night to start a project, collaborate on architecture or request a profile.', 'contact.channel': 'Direct Spectral Channel', 'contact.channelDesc': 'Every message is handled directly by the Alchemist during the 00:00–05:00 AM window.', 'contact.directEmail': 'Direct Email', 'contact.copied': 'Copied', 'contact.timezone': 'Operating Timezone:', 'contact.questStatus': 'Quest Status:', 'contact.available': 'Ready for Projects', 'contact.responseTime': 'Response Time:', 'contact.responsePromise': '< 24 Hours Guaranteed', 'contact.network': 'Digital Network & Profile', 'contact.updated': 'Updated August 2026', 'contact.viewCv': 'View / Download CV', 'contact.success': 'Summoning Successful!', 'contact.successDesc': 'Your signal crossed the night. Receipt:', 'contact.successTail': 'The Alchemist will reply soon!', 'contact.sendAnother': 'Send Another Summoning', 'contact.nameLabel': '1. Traveler / Engineer Name', 'contact.emailLabel': '2. Spectral Address (Email)', 'contact.typeLabel': '3. Quest / Collaboration Type', 'contact.coffeeLabel': '4. Support Coffee Offering', 'contact.messageLabel': '5. Quest Details & Expectations', 'contact.messagePlaceholder': 'Describe the project goal, timeline and any special architecture requirements...', 'contact.submitting': 'Transmitting Signal...', 'contact.submit': 'Summon Ma Cà Tưng', 'contact.projectOther': 'Other Quest', 'contact.coffeeSalt': '1 Midnight Salt Coffee', 'contact.coffeeEspresso': 'Double-Shot Espresso', 'contact.coffeeTea': 'Peach Citrus Lemongrass Tea',
  'mascot.sleeping': '😴 Zzz... Sleeping... (Traveler away)...', 'mascot.expand': 'Expand companion', 'mascot.collapse': 'Minimize to icon', 'mascot.hops': 'hops', 'mascot.pet': 'Ma Cà Tưng Pet', 'mascot.coffee': 'Coffee', 'mascot.coffeeTitle': 'Give Robusta coffee', 'mascot.talisman': 'Seal charm', 'mascot.talismanTitle': 'Apply 0-Bug talisman', 'mascot.petAction': 'Headpat', 'mascot.petTitle': 'Pet Ma Cà Tưng', 'mascot.time': 'Time travel', 'mascot.timeTitle': 'Toggle the 24H time machine', 'mascot.summon': 'Summon Ma Cà Tưng', 'mascot.summonTitle': 'Summon Ma Cà Tưng / Contact',
  'projectModal.featured': 'Featured Architecture', 'projectModal.nda': 'Enterprise NDA', 'projectModal.overview': 'Solution Overview', 'projectModal.metrics': 'Impact & Production Metrics', 'projectModal.highlights': 'Architecture & Technical Highlights', 'projectModal.security': 'Enterprise Security & IP (NDA)', 'projectModal.securityText': 'This is a specialized system serving enterprise infrastructure and operations. To honor client data agreements, source code and live production environments are not public.', 'projectModal.summon': 'Summon a Solution Consultation', 'projectModal.readArticle': 'Read Architecture Article', 'projectModal.close': 'Close [ESC]', 'projectModal.closeAria': 'Close popup',
  'game.rankMaster': '🧙‍♂️ Master Exorcist', 'game.rankSlayer': '⚡ Bug Slayer', 'game.rankCoder': '🌙 Rune Coder', 'game.rankApprentice': '🌱 0-Bug Apprentice', 'game.description': 'Type falling spell-code from the night sky to banish bugs and train your keyboard reflexes.', 'game.beginner': '0-Bug Apprentice (30s)', 'game.normal': 'Midnight Mage (60s)', 'game.boss': 'Boss Bug Survival (5 ❤️)', 'game.score': 'Score', 'game.lives': 'Lives', 'game.time': 'Time', 'game.speed': 'Speed', 'game.accuracy': 'Accuracy', 'game.best': 'Best', 'game.mute': 'Enable Sound', 'game.unmute': 'Disable Sound', 'game.fullscreen': 'Fullscreen', 'game.resume': 'Resume', 'game.pause': 'Pause', 'game.start': 'Start Game', 'game.startHint': 'Press any key or click to start typing', 'game.paused': 'Game Paused', 'game.pauseHint': 'Take a sip of Robusta coffee', 'game.end': 'Exorcism Session Complete!', 'game.totalScore': 'Total Score', 'game.wpm': 'Typing Speed', 'game.replay': 'Play Again', 'game.leaderboard': 'View Leaderboard', 'game.noScores': 'No high scores yet. Be the first to enter the hall of fame!', 'game.cast': '✨ Bug Banished!',
  'forge.title': 'Developer Talisman', 'forge.titleAccent': 'Forge', 'forge.description': 'Choose a guardian spell, enter your name and wish, then perform the blessing ritual to receive 0-bug protection for the repository.', 'forge.presets': '1. Choose a Guardian Spell', 'forge.author': '2. Engineer Name (Author)', 'forge.wish': '3. Wish / Blessing', 'forge.palette': '4. Talisman Palette', 'forge.blessing': 'Invoke Blessing', 'forge.blessingAgain': 'Bless Again', 'forge.blessingProgress': '⏳ Casting blessing...', 'forge.copy': '📋 Copy ASCII Card', 'forge.copied': '✓ ASCII Copied!', 'forge.owner': 'Engineer:', 'forge.wishValue': 'Wish:', 'forge.blessed': '✓ BLESSED', 'forge.notBlessed': '[NOT BLESSED]',
  'theravada.brand': 'Meditation Mage', 'theravada.tagline': 'Mindfulness Every Second • Theravāda', 'theravada.home': 'Back to Macatung.dev', 'theravada.ehipassiko': 'EHIPASSIKO — COME AND SEE & EXPERIENCE', 'theravada.heroTitle': 'Beyond the Darkness of Ignorance', 'theravada.heroAccent': 'Toward the Light of Right Understanding', 'theravada.heroQuote': 'Even Ma Cà Tưng, wandering through the darkness of ignorance, can release delusion when meeting the Dhamma, sit in meditation and find peace and liberation through the Triple Gem.', 'theravada.study': 'Study the Dhamma', 'theravada.practice': 'Practice Vipassanā', 'theravada.chanting': 'Pāḷi Chanting', 'theravada.history': 'Buddhist History', 'theravada.glossary': 'Pāḷi Glossary', 'theravada.verse': 'Dhammapada — Verse', 'theravada.reflect': 'Reflect in Silence', 'theravada.pillars': 'Four Theravāda Pillars', 'theravada.pillarsDesc': 'Study the teachings, lineage and lived truth in each moment.', 'theravada.explore': 'Explore section', 'theravada.core': 'Core Canon & Teachings', 'theravada.recent': 'Recent Suttas & Lessons', 'theravada.read': 'Read article', 'theravada.minutes': 'min read', 'theravada.articles': 'articles',
  'page.aboutTitle': 'Skills & Professional Profile', 'page.aboutDescription': 'Explore the software journey, technical skills, production experience and architecture manifesto.', 'page.projectsTitle': 'Project Grimoire — Production Systems', 'page.projectsDescription': 'Explore software products, system architectures, interactive applications and open-source work.', 'page.contactTitle': 'Summoning & Technical Consultation', 'page.contactDescription': 'Send a summoning message or connect for software development and architecture consulting.', 'page.terminalDescription': 'A virtual zsh shell with 11 magic commands, arrow-key history and mechanical typing sounds.',
});

export function useI18n() {
  if (!initialized && typeof window !== 'undefined') {
    const saved = window.localStorage.getItem('macatung-locale');
    if (saved === 'vi' || saved === 'en') locale.value = saved;
    document.documentElement.lang = locale.value;
    initialized = true;
  }
  const t = (key: string, fallback?: string) => messages[locale.value][key] || fallback || key;
  const setLocale = (next: Locale) => {
    locale.value = next;
    if (typeof window !== 'undefined') {
      window.localStorage.setItem('macatung-locale', next);
      document.documentElement.lang = next;
    }
  };
  return { locale: computed(() => locale.value), t, setLocale };
}
